name: Notely
description: In this blog I will announce updates of the Notely Browser Extension and write about all aspects of web and UX design
url: "http://notely.github.io"
paginate: 5
paginate_path: "blog/page:num"
permalink: "blog/:categories/:title.html"
markdown: maruku
markdown_ext: markdown,mkd,mkdn,md
